Issue 90 fancybox
ledenev-viktor/music-studio pull request #101
Opened 2024-06-16 18:04 UTC by ledenev-viktor

added fancybox
pull request to discuss improvements

2024-06-20 02:16 UTC, ledenev-viktor commented
It turned out that it is impossible to get a full-size image using a regular link from Google Drive. The link for the full-length image is generated only for downloading. Therefore, I had to add a field for the base64 image.
Base64 is registered in the database. Not sure if it's worth doing this. It might be better to code through a Filereader on the front-end.

Among the additional functionality for the admin panel of the main slider, you can add sorting of slides through drag-and-drop.

2024-06-22 17:59 UTC, YuliaKletsova requested changes

2024-06-22 17:59 UTC, YuliaKletsova commented on src/components/ui/admin/settings/listSlides/item.tsx
> +                    <div>
Looks like this div can be removed

2024-06-22 17:59 UTC, YuliaKletsova commented on src/components/widgets/home/mockSlides.ts
Can we remove this?

2024-06-22 17:59 UTC, YuliaKletsova commented on public/parallax-gallery/1.webp
This folder also can be removed

2024-06-22 18:09 UTC, YuliaKletsova commented on pages/api/supabase/settings_preview/get.tsx
Let's call the folder just settings supabase/settings/get

2024-06-22 18:09 UTC, YuliaKletsova commented on src/components/ui/admin/settings/listSlides/item.tsx
> +export const Item = ({
Could we have better naming and call the file Item? And please call the file exactly like component Item

2024-06-22 18:09 UTC, YuliaKletsova commented on src/components/ui/admin/settings/listSlides/types/index.ts
This type can be in the file where you use it.

2024-06-22 18:09 UTC, YuliaKletsova commented on src/components/ui/admin/settings/listSlides/types/index.ts
Seems like it is just one file. But if no okay.

2024-06-22 18:09 UTC, YuliaKletsova commented on src/components/ui/modal/index.tsx
> +export const Modal = styled(ModalAntd)``;
There are no styles.So let's remove this file?

2024-06-23 13:46 UTC, ledenev-viktor commented on pages/api/supabase/settings_preview/get.tsx
We use two tables in our database. SETTINGS table and PREVIEW_SETTINGS table. Therefore, I suggest leaving the directories as they are.

2024-06-23 13:51 UTC, ledenev-viktor commented on src/components/ui/admin/settings/listSlides/types/index.ts
This file used in two different places.

2024-06-25 22:46 UTC, merged